version: '3.8'

services:
  php:
    image: canals/php:latest
    container_name: php_container_gift
    volumes:
      - ./gift.appli/public:/var/www/html
      - ./gift.appli/src:/var/www/src
    ports:
      - "8080:80"
    networks:
      - app-network
    restart: unless-stopped

  api:
    image: canals/php:latest
    container_name: api_container_gift
    volumes:
      - ./gift.api/public:/var/www/html
      - ./gift.api/src:/var/www/src

    ports:
      - "8082:80"
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql_container_gift
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: gift
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container_gift
    environment:
      PMA_HOST: mysql_container_gift
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
