version: '3.8'

services:
  php:
    image: canals/php:latest
    container_name: php_container
    volumes:
      - ./gift.appli/public:/var/www/html
      - ./gift.appli/src:/var/www/src
    ports:
      - "8080:80"
    networks:
      - app-network

  api:
    image: canals/php:latest
    container_name: api_container
    volumes:
      - ./gift.api/public:/var/www/html
      - ./gift.api/src:/var/www/src

    ports:
      - "8082:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gift
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql_container
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
